package org.ds.enums;

public enum CollectionsEnum {
    ARRAYS,
    ARRAYLIST,
    LINKEDLIST,
    COPYONWRITEARRAYLIST,
    VECTOR,
    STACK,
    HASHSET,
    SORTEDSET,
    TREESET,
    LINKEDHASHSET,
    HASHTABLE,
    HASHMAP,
    LINKEDHASHMAP,
    TREEMAP,
    PRIORITYQUEUE,
    LINKEDBLOCKINGQUEUE,
    ARRAYBLOCKINGQUEUE,
    ARRAYDEQUE,
    PRIORITYBLOCKINGQUEUE,
    CONCURRENTHASHMAP
}
